imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }



fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Collab\UserBundle\Entity\User
    service:
         user_manager: pugx_user_manager
    registration:
         form:
            type: collab_user_registration



pugx_multi_user:
    users:
      user_one:
         entity:
            class: Collab\UserBundle\Entity\Etudiant
            #          factory:
         registration:
            form:
              type: Collab\UserBundle\Form\Type\RegistrationEtudiantFormType
              name: fos_user_registration_form
              validation_groups:  [Registration, Default]
            template: CollabUserBundle:Registration:user_one.form.html.twig
         profile:
            form:
              type: Collab\UserBundle\Form\Type\ProfileEtudiantFormType
              name: fos_user_profile_form
              validation_groups:  [Profile, Default]
      user_two:
         entity:
            class: Collab\UserBundle\Entity\Enseignant
         registration:
            form:
              type: Collab\UserBundle\Form\Type\RegistrationEnseignantFormType
              name: fos_user_registration_form
              validation_groups:  [Registration, Default]
            template: CollabUserBundle:Registration:user_two.form.html.twig
         profile:
            form:
              type: Collab\UserBundle\Form\Type\ProfileEnseignantFormType
              name: fos_user_profile_form
              validation_groups:  [Profile, Default]


      user_three:
         entity:
            class: Collab\UserBundle\Entity\Admin
         registration:
            form:
              type: Collab\UserBundle\Form\Type\RegistrationAdminFormType
              name: fos_user_registration_form
              validation_groups:  [Registration, Default]
            template: CollabUserBundle:Registration:user_three.form.html.twig
         profile:
            form:
              type: Collab\UserBundle\Form\Type\ProfileAdminFormType
              name: fos_user_profile_form
              validation_groups:  [Profile, Default]